# This is a stub file only used for tests

wifi_ssid: test
wifi_password: "12345678"
wifi_ap_password: "12345678"

generic_plug_01_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
generic_plug_01_ota_password:

generic_plug_02_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
generic_plug_02_ota_password:

generic_plug_03_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
generic_plug_03_ota_password:

_3d_printer_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
_3d_printer_ota_password:

bedroom_light_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
bedroom_light_ota_password:

christmas_tree_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
christmas_tree_ota_password:

yoann_office_meetings_lights_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
yoann_office_meetings_lights_ota_password:

yoann_office_co2_sensor_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
yoann_office_co2_sensor_ota_password:

garage_light_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
garage_light_ota_password:

frontdoor_light_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
frontdoor_light_ota_password:

shed_controller_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
shed_controller_ota_password:

yoann_office_light_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
yoann_office_light_ota_password: