#
# Extensible Lilygo T-Relay-8 ESP32 controller for the shed
#

substitutions:
  device_id: shed_controller
  device_name: shed-controller
  friendly_name: Shed Controller

esphome:
  name: "${device_name}"
  comment: "${friendly_name}"

esp32:
  board: esp32dev

<<:
  !include {
    file: "common/networking.yaml",
    vars:
      {
        device_id: "${device_id}",
        wifi_ssid: !secret wifi_ssid,
        wifi_password: !secret wifi_password,
        wifi_ap_password: !secret wifi_ap_password,
        encryption_key: !secret shed_controller_encryption_key,
        ota_password: !secret shed_controller_ota_password,
      },
  }

logger:
  baud_rate: 0 # Disable UART logging

external_components:
  - source: github://Fabian-Schmidt/esphome-victron_ble

# Bluetooth hub
esp32_ble_tracker:

victron_ble:
  - id: smartshunt
    mac_address: !secret shed_controller_smartshunt_mac_address
    bindkey: !secret shed_controller_smartshunt_encryption_key

  - id: smartsolar
    mac_address: !secret shed_controller_smartsolar_mac_address
    bindkey: !secret shed_controller_smartsolar_encryption_key

status_led:
  #
  # Status led
  #
  pin:
    number: GPIO25

switch:
  #
  # Relays
  #
  - platform: gpio
    pin: GPIO33
    id: "${device_id}_relay_1"
    name: "${friendly_name} Relay 1"
  - platform: gpio
    pin: GPIO32
    id: "${device_id}_relay_2"
    name: "${friendly_name} Relay 2"
  - platform: gpio
    pin: GPIO13
    id: "${device_id}_relay_3"
    name: "${friendly_name} Relay 3"
  - platform: gpio
    pin: GPIO12
    id: "${device_id}_relay_4"
    name: "${friendly_name} Relay 4"
  - platform: gpio
    pin: GPIO21
    id: "${device_id}_relay_5"
    name: "${friendly_name} Relay 5"
  - platform: gpio
    pin: GPIO19
    id: "${device_id}_relay_6"
    name: "${friendly_name} Shed Outdoor String Light"
  - platform: gpio
    pin: GPIO18
    id: "${device_id}_relay_7"
    name: "${friendly_name} Relay 7"
  - platform: gpio
    pin: GPIO5
    id: "${device_id}_relay_8"
    name: "${friendly_name} Battery Warmer"
  - platform: template
    id: "${device_id}_inverter"
    name: "${friendly_name} Inverter"
    turn_on_action:
      - switch.turn_on: "${device_id}_relay_7"
      - delay: 500ms
      - switch.turn_off: "${device_id}_relay_7"

sensor:
  #
  # Common: wifi + uptime
  #
  - !include ./common/sensor.wifi_signal.yaml
  - !include ./common/sensor.uptime.yaml

  #
  # Victron
  #
  - platform: victron_ble
    victron_ble_id: smartshunt
    name: "Current"
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: smartsolar
    name: "Battery Voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: smartsolar
    name: "Battery Current"
    type: BATTERY_CURRENT

text_sensor:
  #
  # Common: ESPHome version
  #
  - !include ./common/text_sensor.version.yaml

binary_sensor:
  #
  # Inverter remote
  #
  - platform: gpio
    pin:
      number: GPIO22
      inverted: true
      mode:
        input: true
        pullup: true
    name: inverter-on
  - platform: gpio
    pin:
      number: GPIO26
      inverted: true
      mode:
        input: true
        pullup: true
    name: inverter-error
