substitutions:
  name: garage-door-1
  friendly_name: ratgdov2.5i 30f724
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret garage_door_1_encryption_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
